<?php
#
# File generated by Dolibarr installer 3.1.0 on 2011-11-06 22:01:28
#
# Take a look at conf.php.example file for an example of conf.php file
# and explanations for all possibles parameters.
#
$dolibarr_main_url_root='http://billing.webblower.com';
$dolibarr_main_document_root='/home/webbrcom/public_html/billing';
#$dolibarr_main_url_root_alt='http://billing.webblower.com/custom';
#$dolibarr_main_document_root_alt='/home/webbrcom/public_html/billing/custom';
$dolibarr_main_data_root='/home/webbrcom/public_html/billing/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='webbrcom_billing';
$dolibarr_main_db_user='webbrcom_biling';
$dolibarr_main_db_pass='enteraja';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
$dolibarr_main_authentication='dolibarr';

# Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='b4cbec30875520289b1311001565937b';
$dolibarr_mailing_limit_sendbyweb='0';
?>